-- Tech It Out database
create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  phone text,
  type text,
  category text,
  message text not null,
  status text not null default 'unread'
);

create index if not exists enquiries_created_at_idx on public.enquiries(created_at desc);
create index if not exists enquiries_status_idx on public.enquiries(status);

-- The website server uses the Supabase service role key.
-- Do not expose that key in browser JavaScript.
alter table public.enquiries enable row level security;

-- No public browser policies are intentionally created.
-- Server-side API access is used for inserts and admin reads.